config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  Sidekiq::Web.use(Rack::Auth::Basic) do |user_id, password|
    [user_id, password] == [ENV['SIDEKIQ_BASIC_ID'], ENV['SIDEKIQ_BASIC_PASSWORD']]
  end
  mount Sidekiq::Web, at: '/sidekiq'
  get 'rewiews/new'
  get 'rewiews/create'
  get 'users/show'
  root "static_pages#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/auth/failure' => 'omniauth_callbacks#failure'
  end
  get 'spot_images/:photo_reference', to: 'spot_images#show', as: 'spot_image_proxy'
  get 'static_pages/index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'spots/list', to: 'spots#list'
  get 'reviews/search', to: 'reviews#search'
  get 'proxy_image', to: 'spots#proxy_image'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['BUCKET_NAME']}/sitemaps/sitemap.xml.gz")
  resources :spots, only: %i[index show] do
    get 'tag_filter/:tag_id', to: 'spots#index', as: :tag_filter_reviews
    resources :reviews, only: %i[new create show edit update destroy]
    collection do
      get :bookmarks
      get :map
      get :search
      get :visits
    end
  end
  resources :screenshots, only: [:create] do
    collection do
      post :update_meta_tags
    end
  end
  resources :spot_bookmarks, only: %i[create destroy]
  resources :helpfuls, only: %i[create destroy]
  resources :visits, only: %i[create destroy]
  resources :tags, only: %i[] do
    collection do
      get :search
    end
  end
  resources :diagnostics, only: [] do
    member do
      get 'question', to: 'diagnostics#show_question', as: 'question'
      post 'answer_question', to: 'diagnostics#answer_question'
    end
    collection do
      get 'start', to: 'diagnostics#start'
      get 'result', to: 'diagnostics#result'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/spot.rb
class Spot < ApplicationRecord
  require 'open-uri'
  require 'mini_magick'
  mount_uploader :ogp_image, ProcessedImageUploader
  before_save :generate_ogp_image, if: :should_generate_ogp_image?
  
  acts_as_mappable default_units: :kms,
                   default_formula: :sphere,
                   distance_field_name: :distance,
                   lat_column_name: :latitude,
                   lng_column_name: :longitude

  enum foster_parents: { no_recruitment: 0, recruitment: 1 }
  enum adoption_event: { unheld: 0, held: 1 }
  enum age_limit: { no_listed: 0, unlimited: 1, walking_age: 2, three_and_above: 3, four_and_above: 4, six_and_above: 6, ten_and_above: 10, middle_school_and_above: 12 }

  has_many :spot_images, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :spot_bookmarks, dependent: :destroy
  has_many :visits, dependent: :destroy
  belongs_to :category
  belongs_to :prefecture, class_name: 'Prefecture', foreign_key: 'prefecture_id', optional: true
  validates :name, :latitude, :longitude, :place_id, presence: true, uniqueness: true  
  
  #enumの日本語化
  def foster_parents_i18n
    I18n.t("enums.spot.foster_parents.#{foster_parents}")
  end

  def adoption_event_i18n
    I18n.t("enums.spot.adoption_event.#{adoption_event}")
  end

  def age_limit_i18n
    I18n.t("enums.spot.age_limit.#{age_limit}")
  end

  # タグに基づいたスポットをフィルタリングするスコープ
  scope :with_tag, -> (tag_name) {
    joins(reviews: :tags).where(tags: { name: tag_name }).distinct
  }

  # Ransackで検索可能なカスタムスコープを指定
  def self.ransackable_scopes(auth_object = nil)
    %i[with_tag]
  end



  # 猫の画像を優先的に表示させるメソッド
  def prioritized_spot_image #SpotImageの中で、cat属性がtrueのものを優先的に取得し、存在しない場合は最初のSpotImageを取得する
    spot_images.find_by(cat: true) || spot_images.first
  end

  def process_image(image_url)
    # URLから画像を取得
    temp_file = Tempfile.new(['processed_image', '.png'], encoding: 'ascii-8bit')
    URI.open(image_url) do |image|
      temp_file.binmode
      temp_file.write(image.read)
      temp_file.rewind
    end
  
    # MiniMagickを使用して画像を加工
    image = MiniMagick::Image.open(temp_file.path)
    image.resize "1200x630"
    image.format "webp"
    image.write(temp_file.path)
  
    # CarrierWave::SanitizedFileオブジェクトを作成
    sanitized_file = CarrierWave::SanitizedFile.new(temp_file)
  
    # Uploaderを使用して画像を保存
    uploader = ProcessedImageUploader.new(self)
    uploader.store!(sanitized_file)

    # `ogp_image` カラムを更新
    self.ogp_image = uploader.file
  
    # 一時ファイルを閉じて削除
    temp_file.close
    temp_file.unlink

    # デバッグメッセージ
    puts "Uploader URL: #{uploader.url(:ogp)}"
  
    # 加工された画像のURLを返す
    uploader.url(:ogp)
  end

  # Geocoding setup
  geocoded_by :address  # 使用する地名解決にはaddress属性を利用（ここはモデルの実際の属性に依存）
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def self.ransackable_attributes(auth_object = nil)
    ["address", "category_id", "created_at", "id", "latitude", "longitude", "name", "opening_hours", "phone_number", "place_id", "postal_code", "prefecture_id", "rating", "updated_at", "web_site","foster_parents","adoption_event"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category", "prefecture", "spot_images"]
  end

  private

  def default_image_url
    ActionController::Base.helpers.asset_path('default.webp')
  end

  def generate_ogp_image
    if prioritized_spot_image.present?
      proxy_image_url = Rails.application.routes.url_helpers.proxy_image_url(photo_reference: prioritized_spot_image.image, host: Rails.env.production? ? 'https://nekospot.jp' : 'http://localhost:3000')
      self.ogp_image = process_image(proxy_image_url)
    end
  end

  def should_generate_ogp_image?
    ogp_image.blank? || prioritized_spot_image.image_changed?
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  require 'open-uri'
  before_action :set_map_data, only: [:map, :list]

  def index
    review = Review.last
    @user = review.user if review.present?
    @categories = Category.all
    @prefectures = Prefecture.all
    @tags = Tag.all
    # params[:q][:adoption_event_eq]が配列になっている場合に対応
    if params[:q] && params[:q][:adoption_event_eq].is_a?(Array)
      params[:q][:adoption_event_eq] = params[:q][:adoption_event_eq].first
    end
    @q_spots = Spot.ransack(params[:q])
    page_param = params[:page].is_a?(Array) ? params[:page].first : params[:page]
    sorted_spots = apply_sort_scope(@q_spots.result(distinct: true))
    @spots = sorted_spots.includes(:spot_images, :category).page(page_param.to_i).per(12)
    Rails.logger.debug "SQL Query for spots: #{@spots.to_sql}"
    @spots_count = sorted_spots.count
    @current_sort = params.dig(:q, :s) || "created_at asc"
    
    @q_reviews = Review.ransack(params[:q])

    if params[:tag_id].present?
      filtered_reviews = Review.review_tag(params[:tag_id])
      @reviews = filtered_reviews.includes(:user, :spot, :tags).page(params[:page]).per(12)
    else
      filtered_reviews = @q_reviews.result(distinct: false).includes(:user, :spot, :tags)
      #distinct_reviews = filtered_reviews.select('DISTINCT ON (reviews.id) reviews.id, reviews.user_id, reviews.spot_id, reviews.rating, reviews.body, reviews.created_at, reviews.updated_at, reviews.images')
      @reviews = filtered_reviews.page(params[:page]).per(12)
    end
  end

  def map
    @tags = Tag.all
    @categories = Category.all
    @prefectures = Prefecture.all
    @user = current_user
    @q = Spot.ransack(params[:q])
    @spots = @q.result(distinct: true).includes(:spot_images, :category)
  
    if params[:category].present?
      @spots = @spots.where(category_id: params[:category])
    end
    
    respond_to do |format|
      format.html
      format.json { render json: @spots.as_json(include: [:spot_images, :category]) }
    end
  end

  def list
    @q = Spot.ransack(params[:q])
    search_results = @q.result(distinct: true)

    latitude = params[:latitude].to_f
    longitude = params[:longitude].to_f
    radius = params[:radius] || 10 # デフォルトは10km

    if params[:category].present?
      search_results = search_results.where(category_id: params[:category])
    end
    
    @spots = search_results.includes(:spot_images, :category).near([latitude, longitude], radius, units: :km).limit(10)

    # JSON形式でスポットのデータをフロントエンドに送り返す
    spots_json = @spots.map do |spot|
      spot.as_json(only: [:id, :name, :latitude, :longitude, :address, :rating]).merge(
        image: spot.prioritized_spot_image&.image,
        category: spot.category.name,
        category_id: spot.category.id
      )
    end

    render json: spots_json
  end

  def bookmarks
    @q = current_user.spot_bookmarks.joins(:spot).ransack(params[:q])
    @bookmark_spots = @q.result(distinct: true).includes(:spot).order(created_at: :desc)

    bookmarked_spots = current_user.spot_bookmarks.joins(:spot).map(&:spot)
    @categories = bookmarked_spots.map(&:category).uniq
    prefecture_ids = bookmarked_spots.map(&:prefecture_id).uniq
    @prefectures = Prefecture.find(prefecture_ids)
    @visited_spots = current_user.visits.includes(:user).order(created_at: :desc)
  end

  def visits
    @visited_spots = current_user.visits.includes(:user).order(created_at: :desc)
  end

  def show
    @user = current_user
    @spot = Spot.find(params[:id])
    Rails.logger.debug "Received tag_id: #{params[:tag_id]}" # デバッグ用ログ
    @review = Review.new(spot: @spot)
    if params[:tag_id].present?
      @reviews = @spot.reviews.joins(:tags).where(tags: { id: params[:tag_id] }).includes(:user).order(created_at: :desc).page(params[:page]).per(10)
      logger.debug "Filtered reviews for tag_id: #{params[:tag_id]}"
    else
      @reviews = @spot.reviews.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
      logger.debug "No tag_id provided, showing all reviews"
    end
    @all_reviews_count = @spot.reviews.count
    @average_rating = @spot.reviews.average(:rating).to_f
    @prioritized_image = @spot.prioritized_spot_image # 優先的に表示する画像を取得
    @image_url = @spot.ogp_image
  end

  def search
    query = params[:q]
    if query.present?
      @spots = Spot.ransack(name_or_address_cont: query).result
      @search_by_name = Spot.ransack(name_cont: query).result.exists?
      @search_by_address = Spot.ransack(address_cont: query).result.exists?
    else
      @spots = Spot.none
      @search_by_name = false
      @search_by_address = false
    end

    respond_to do |format|
      format.html # For normal HTML requests
      format.json # For AJAX requests
    end
  end

  def proxy_image
    photo_reference = params[:photo_reference]
    url = "https://maps.googleapis.com/maps/api/place/photo?maxheight=1000&photo_reference=#{photo_reference}&key=#{ENV['GMAP_API_KEY']}"
    
    begin
      image_data = URI.open(url).read
      send_data image_data, type: 'image/jpeg', disposition: 'inline'
    rescue OpenURI::HTTPError => e
      render plain: "Image not found", status: :not_found
    rescue => e
      render plain: "An error occurred: #{e.message}", status: :internal_server_error
    end
  end

  private

  def apply_sort_scope(spots)
    case params[:q]&.dig(:s)
    when 'rating desc'
      Rails.logger.debug "Applying sorted_by_rating scope"
      spots.reorder(Arel.sql('rating DESC NULLS LAST'))
    when 'created_at asc'
      Rails.logger.debug "Applying sorted_by_created_at_asc scope"
      spots.reorder(:created_at)
    when 'created_at desc'
      Rails.logger.debug "Applying sorted_by_created_at_desc scope"
      spots.reorder(created_at: :desc)
    else
      Rails.logger.debug "No specific sorting applied"
      spots
    end
  end

  def set_map_data
    @q = Spot.ransack(params[:q])  # フリーワード検索のパラメータを受け取る
    @spots = @q.result(distinct: true).includes(:spot_images, :category)

    gon.api_key = ENV['GMAP_API_KEY']
    gon.spots = @spots.map do |spot|
      spot.as_json(only: [:id, :name, :latitude, :longitude, :address, :rating]).merge(
        image: spot.prioritized_spot_image&.image,
        category: spot.category.name,
        category_id: spot.category.id
      )
    end
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_bookmark.html.erb
<% if spot.present? %>
  <%= link_to spot_bookmarks_path(spot_id: spot.id), id: "bookmark-button-for-spot-#{spot.id}", data: { turbo_method: :post }, class: "inline-flex flex-col items-center justify-center px-2 rounded-full group" do %>
    <i class="ph-fill ph-heart fa-xl w-full h-3 mt-2 text-gray-400"></i>
    <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral"><%= spot.spot_bookmarks.count %></span>
  <% end %>
<% else %>
  <p>スポット情報がありません</p>
<% end %>

app/views/spots/_no_review_drawer_swipe.html.erb
<div id="no-review-drawer-swipe" class="md:hidden fixed z-40 w-full overflow-y-auto bg-white border-t border-gray-200 rounded-t-lg dark:border-gray-700 dark:bg-gray-800 transition-transform bottom-0 left-0 right-0 translate-y-full bottom-[60px]" tabindex="-1" aria-labelledby="drawer-swipe-label">
    <div class="p-4 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-700" data-drawer-toggle="no-review-drawer-swipe">
        <span class="absolute w-8 h-1 -translate-x-1/2 bg-gray-300 rounded-lg top-3 left-1/2 dark:bg-gray-600"></span>
        <h5 id="drawer-swipe-label" class="inline-flex items-center text-base text-gray-500 dark:text-gray-400 font-medium">
        <i class="ph-bold ph-list-magnifying-glass fa-2xl text-primary-hover"></i>&ensp;絞り込み</h5>
    </div>
    <div data-controller="autocomplete" data-autocomplete-url-value="/reviews/search" role="combobox">
        <%= search_form_for @q_reviews, url: spots_path, html: { id: "searchForm", class: "max-w-lg mx-auto py-4 px-8", data: { turbo_frame: "reviews-list" } }  do |f| %>
            <label for="" class="mb-2 text-sm font-medium text-secondary sr-only dark:text-white">検索</label>
            <div class="relative">
                <div class="absolute inset-y-4 md:inset-y-3 start-0 flexed items-center ps-3 pointer-events-none">
                    <i class="ph ph-magnifying-glass text-secondary"></i>
                </div>
                <%= f.search_field :spot_name_or_spot_address_or_body_cont, data: { autocomplete_target: 'input' }, class: 'block w-full p-4 md:p-3 ps-10 md:ps-8 text-sm text-secondary border border-secondary rounded-full bg-white focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder: '猫スポット名または住所' %>
                <%= f.hidden_field :spot_name, data: { autocomplete_target: 'hidden' } %>
                <%= f.hidden_field :spot_address, data: { autocomplete_target: 'hidden' } %>
                <%= f.hidden_field :body, data: { autocomplete_target: 'hidden' } %>
                <ul class="list-group absolute w-full bg-white p-2 shadow z-[1] rounded-box" data-autocomplete-target="results"></ul>
            </div>
            <div class="flex md:flex-col md:space-y-3 md:space-x-0 space-x-4 mt-8 text-secondary">
                <div class='label-select h-full md:w-full w-1/2 text-sm'>
                    <%= f.label :spot_category_id_eq, 'カテゴリ', class: 'label text-sm font-semibold' %>
                    <%= f.collection_select :spot_category_id_eq, @categories, :id, :name,  { include_blank: '指定なし' }, { class: 'search-select bg-gray-50 border border-gray-300 text-secondary text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' } %>
                </div>
                <div class='label-select h-full md:w-full w-1/2 text-sm md:mb-8'>
                    <%= f.label :spot_prefecture_id_eq, '都道府県', class: 'label text-sm font-semibold' %>
                    <%= f.collection_select :spot_prefecture_id_eq, @prefectures, :id, :name,  { include_blank: '指定なし' }, { class: 'search-select bg-gray-50 border border-gray-300 text-secondary text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' } %>
                </div>
            </div>
            <div class="flex justify-center items-center mb-16 mt-8">
                <%= f.submit 'この条件で検索する', class: 'font-semibold text-sm rounded-md relative inline-flex group items-center justify-center px-3.5 py-2 m-1 cursor-pointer border-b-4 border-l-2 active:border-accent active:shadow-none shadow-lg bg-gradient-to-tr from-accent to-accent-active border-accent-hover text-white' do %>
                    <span class="absolute w-0 h-0 transition-all duration-300 ease-out bg-white rounded-full group-hover:w-32 group-hover:h-32 opacity-10"></span>
                    <span class="relative"></span>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/spots/_review_drawer_swipe.html.erb
<div id="review-drawer-swipe" class="md:hidden fixed z-40 w-full overflow-y-auto bg-white border-t border-gray-200 rounded-t-lg dark:border-gray-700 dark:bg-gray-800 transition-transform bottom-0 left-0 right-0 translate-y-full bottom-[60px]" tabindex="-1" aria-labelledby="drawer-swipe-label">
    <div class="p-4 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-700" data-drawer-toggle="review-drawer-swipe">
        <span class="absolute w-8 h-1 -translate-x-1/2 bg-gray-300 rounded-lg top-3 left-1/2 dark:bg-gray-600"></span>
        <h5 id="drawer-swipe-label" class="inline-flex items-center text-base text-gray-500 dark:text-gray-400 font-medium">
        <i class="ph-bold ph-list-magnifying-glass fa-2xl text-primary-hover"></i>&ensp;絞り込み</h5>
    </div>
    <div data-controller="autocomplete" data-autocomplete-url-value="/reviews/search" role="combobox">
        <%= search_form_for @q_reviews, url: spots_path, html: { id: "searchForm", class: "max-w-lg mx-auto py-4 px-8", data: { turbo_frame: "reviews-list" } }  do |f| %>
            <label for="" class="mb-2 text-sm font-medium text-secondary sr-only dark:text-white">検索</label>
            <div class="relative">
                <div class="absolute inset-y-4 md:inset-y-3 start-0 flexed items-center ps-3 pointer-events-none">
                    <i class="ph ph-magnifying-glass text-secondary"></i>
                </div>
                <%= f.search_field :spot_name_or_spot_address_or_body_cont, data: { autocomplete_target: 'input' }, class: 'block w-full p-4 md:p-3 ps-10 md:ps-8 text-sm text-secondary border border-secondary rounded-full bg-white focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder: '猫スポット名または住所' %>
                <%= f.hidden_field :spot_name, data: { autocomplete_target: 'hidden' } %>
                <%= f.hidden_field :spot_address, data: { autocomplete_target: 'hidden' } %>
                <%= f.hidden_field :body, data: { autocomplete_target: 'hidden' } %>
                <ul class="list-group absolute w-full bg-white p-2 shadow z-[1] rounded-box" data-autocomplete-target="results"></ul>
            </div>
            <div class="flex md:flex-col md:space-y-3 md:space-x-0 space-x-4 mt-8 text-secondary">
                <div class='label-select h-full md:w-full w-1/2 text-sm'>
                    <%= f.label :spot_category_id_eq, 'カテゴリ', class: 'label text-sm font-semibold' %>
                    <%= f.collection_select :spot_category_id_eq, @categories, :id, :name,  { include_blank: '指定なし' }, { class: 'search-select bg-gray-50 border border-gray-300 text-secondary text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' } %>
                </div>
                <div class='label-select h-full md:w-full w-1/2 text-sm md:mb-8'>
                    <%= f.label :spot_prefecture_id_eq, '都道府県', class: 'label text-sm font-semibold' %>
                    <%= f.collection_select :spot_prefecture_id_eq, @prefectures, :id, :name,  { include_blank: '指定なし' }, { class: 'search-select bg-gray-50 border border-gray-300 text-secondary text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' } %>
                </div>
            </div>
            <div class="flex justify-center items-center mb-16 mt-8">
                <%= f.submit 'この条件で検索する', class: 'font-semibold text-sm rounded-md relative inline-flex group items-center justify-center px-3.5 py-2 m-1 cursor-pointer border-b-4 border-l-2 active:border-accent active:shadow-none shadow-lg bg-gradient-to-tr from-accent to-accent-active border-accent-hover text-white' do %>
                    <span class="absolute w-0 h-0 transition-all duration-300 ease-out bg-white rounded-full group-hover:w-32 group-hover:h-32 opacity-10"></span>
                    <span class="relative"></span>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/spots/_review_tab.html.erb
<a class="bg-white inline-block py-2 px-4 rounded-t-lg text-secondary hover:text-neutral font-semibold no-underline rounded-t-lg" id="review_tab" href="#">口コミ(<%= @reviews.present? ? @all_reviews_count : 0 %>件)</a>

app/views/spots/_spot.html.erb
<div class="bg-white shadow-sm flex flex-col mx-auto w-full h-full border rounded-xl md:mb-50 hover:shadow-lg group my-3">
    <div class="flex-shrink-0 rounded-t-xl rounded-b-none relative overflow-hidden h-32 md:h-42 w-full ">
        <%= link_to spot_path(spot), data: { turbo: false } do %>
            <% prioritized_image = spot.prioritized_spot_image %>
            <% if prioritized_image.present? %>
                <%= image_tag spot_image_proxy_url(prioritized_image.image), class: "w-full h-full absolute rounded-t-xl md:rounded-b-none top-0 left-0 md:left-none object-cover transition-transform duration-200 ease-in-out group-hover:scale-110 group-hover:rounded-xl", alt: "Image Description" %>
            <% else %>
                <% image_tag('default.webp', class: "h-full absolute rounded-t-xl rounded-b-none top-0 left-1/2 transform -translate-x-1/2 md:left-none object-cover transition-transform duration-200 ease-in-out group-hover:scale-110 group-hover:rounded-xl")%>
            <% end %>
        <% end %>
    </div>
    <div class="flex flex-wrap w-full md:h-full h-28">
        <div class="p-2 md:p-2.5 flex flex-col h-full sm:p-7 w-full relative">
            <div class="bg-accent absolute top-0 -mt-3 flex items-center font-semibold px-3 py-1.5 leading-none w-auto rounded-full text-xs uppercase text-white">
                <span><i class="ph-fill ph-star fa-lg"></i> <%= spot.rating.nil? ? '評価なし' : spot.rating %></span>
            </div>
            <p class="md:px-1.5 mt-2 text-[10px] text-secondary dark:text-neutral-500"><%= spot.category.name %> / <%= formatted_address(spot.address) %></p>
            <%= link_to spot_path(spot), data: { turbo: false } do %>
                <div class="font-bold text-sm text-neutral font-zenmaru md:px-1.5 overflow-hidden w-full whitespace-nowrap text-overflow-ellipsis break-words whitespace-pre-wrap"><%= spot.name %></div>
            <% end %>
            <div class="justify-between flex items-end h-full md:space-x-4 space-x-2">
                <div class="flex space-x-2">
                    <div class="flex space-x-2 md:mb-1">
                    <% if spot.foster_parents_before_type_cast == 1 %>
                        <div class="bg-primary px-2 py-1 rounded-md shadow-md text-secondary font-semibold text-sm items-center font-zenmaru">里</div>
                    <% end %>
                    <% if spot.adoption_event_before_type_cast == 1 %>
                        <div class="bg-primary px-2 py-1 rounded-md shadow-md text-secondary font-semibold text-sm items-center font-zenmaru">譲</div>
                    <% end %>
                    <% if spot.age_limit_before_type_cast == 1 %>
                        <div class="hidden">
                            <p class="text-xs text-white py-1 px-2 rounded-full bg-accent dark:text-neutral-500"><%= spot.age_limit_i18n %></p>
                        </div>
                    <% end %>
                </div>
                </div>
                <div class="flex">
                    <%= render 'visited_buttons', { spot: spot } %>
                    <%= render 'bookmark_buttons', { spot: spot } %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/spots/_unbookmark.html.erb
<%= link_to spot_bookmark_path(current_user.spot_bookmarks.find_by(spot_id: spot.id)), id: "unbookmark-button-for-spot-#{spot.id}", data: { turbo_method: :delete }, class: "inline-flex flex-col items-center justify-center px-2 rounded-full group" do %>
    <i class="ph-fill ph-heart fa-xl w-full h-3 mt-2 fa-lg text-red-700"></i>
    <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral"><%= spot.spot_bookmarks.count %></span>
<% end %>

app/views/spots/_visited.html.erb
  <%= link_to visits_path(spot_id: spot.id), id: "visited-button-for-spot-#{spot.id}", data: { turbo_method: :post }, class: "inline-flex flex-col items-center justify-center px-2 rounded-full group" do %>
    <i class="ph-fill ph-seal-check fa-xl w-full h-3 mt-2 text-gray-400"></i>
    <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral"><%= spot.visits.count %></span>
  <% end %>