config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  Sidekiq::Web.use(Rack::Auth::Basic) do |user_id, password|
    [user_id, password] == [ENV['SIDEKIQ_BASIC_ID'], ENV['SIDEKIQ_BASIC_PASSWORD']]
  end
  mount Sidekiq::Web, at: '/sidekiq'
  get 'rewiews/new'
  get 'rewiews/create'
  get 'users/show'
  root "static_pages#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/auth/failure' => 'omniauth_callbacks#failure'
  end
  get 'spot_images/:photo_reference', to: 'spot_images#show', as: 'spot_image_proxy'
  get 'static_pages/index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'spots/list', to: 'spots#list'
  get 'reviews/search', to: 'reviews#search'
  get 'proxy_image', to: 'spots#proxy_image'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['BUCKET_NAME']}/sitemaps/sitemap.xml.gz")
  resources :spots, only: %i[index show] do
    get 'tag_filter/:tag_id', to: 'spots#index', as: :tag_filter_reviews
    resources :reviews, only: %i[new create show edit update destroy]
    collection do
      get :bookmarks
      get :map
      get :search
      get :visits
    end
  end
  resources :screenshots, only: [:create] do
    collection do
      post :update_meta_tags
    end
  end
  resources :spot_bookmarks, only: %i[create destroy]
  resources :helpfuls, only: %i[create destroy]
  resources :visits, only: %i[create destroy]
  resources :tags, only: %i[] do
    collection do
      get :search
    end
  end
  resources :diagnostics, only: [] do
    member do
      get 'question', to: 'diagnostics#show_question', as: 'question'
      post 'answer_question', to: 'diagnostics#answer_question'
    end
    collection do
      get 'start', to: 'diagnostics#start'
      get 'result', to: 'diagnostics#result'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :reviews, dependent: :destroy
  has_many :spot_bookmarks, dependent: :destroy
  has_many :bookmark_spots, through: :spot_bookmarks, source: :spot
  has_many :helpfuls, dependent: :destroy
  has_many :helpful_reviews, through: :helpfuls, source: :review
  has_many :visits, dependent: :destroy
  has_many :visited_spots, through: :visits, source: :spot

  enum role: { general: 0, admin: 1 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: %i[google_oauth2 line]

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end
            
  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]
      
    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
  end
            
  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end

  def bookmark(spot)
    bookmark_spots << spot
  end

  def unbookmark(spot)
    bookmark_spots.destroy(spot)
  end

  def bookmark?(spot)
    bookmark_spots.include?(spot)
  end

  def helpful(review)
    helpful_reviews << review
  end

  def unhelpful(review)
    helpful_reviews.destroy(review)
  end

  def helpful?(review)
    helpful_reviews.include?(review)
  end

  def visited(spot)
    visited_spots << spot
  end

  def unvisited(spot)
    visited_spots.destroy(spot)
  end

  def visited?(spot)
    visited_spots.include?(spot)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

def update
  self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

  if validate_avatar(account_update_params[:avatar]) && resource.update(account_update_params)
    redirect_to users_show_path(current_user)
    flash.now[:notice] = "ユーザー情報を更新しました"
  else
    render :edit, status: :unprocessable_entity
  end
end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end

  def validate_avatar(avatar)
    return true if avatar.blank?

    result = Vision.image_analysis(avatar)

    unless result
      flash[:error] = '不適切な画像です'
      return false
    end

    true
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    # 明示的にRedisからセッションを削除する
    if session[:session_id]
      redis_store = ActiveSupport::Cache::RedisStore.new(url: ENV['REDIS_URL'], namespace: 'session')
      redis_store.delete(session[:session_id])
    end

    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @reviews = @user.reviews.includes(:spot).order(created_at: :desc).page(params[:page]).per(10)
    @total_helpfuls = @user.reviews.joins(:helpfuls).count
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_reviews.html.erb
<% @reviews.each do |review| %>
    <div class="flex flex-col gap-3 px-4 py-6 md:p-6 space-y-2">
    <div class="flex">
        <div>
        <span class="block text-sm text-neutral"><%= review.spot.name %></span>
        <span class="block text-xs text-secondary"><%= review.created_at.strftime('%Y/%m/%d') %></span>
        </div>
    </div>
    <div class="-ml-1 flex gap-0.5">  
        <% rating = review.rating %>
        <% full_stars = rating %>
        <% empty_stars = 5 - rating %>
        
        <% full_stars.times do %>
        <i class="ph-fill ph-star fa-lg text-yellow-400"></i>
        <% end %>
        
        <% empty_stars.times do %>
        <i class="ph-fill ph-star fa-lg text-gray-100"></i>
        <% end %>
    </div>
  <!-- stars - end -->
  <p class="text-secondary"><%= review.body %></p>
</div>
  <% end %>

app/views/users/show.html.erb
<% content_for(:title, t('users.show.title')) %>
<div id="flash">
    <%= render 'layouts/flash_messages', flash: flash %>
</div>
<div class="bg-primary md:pb-16 md:mb-0 mb-20">
    <div class="flex flex-col items-center justify-center w-full md:pt-20">
        <div class="md:w-11/12 w-full">
            <div data-controller="tabs rounded-t-lg" data-tabs-active-tab-class="-mb-px border-l border-t border-r rounded-t-lg">
                <ul class="list-reset flex border-b rounded-t-lg">
                    <li class="-mb-px mr-1 w-1/2 bg-white rounded-t-lg text-center" data-tabs-target="tab" data-action="click->tabs#change">
                        <a class="bg-white inline-block py-2 px-4 rounded-t-lg text-secondary hover:text-neutral font-semibold no-underline rounded-t-lg" href="#" data-turbo="false">ユーザー情報</a>
                    </li>
                </ul>
                <div id="mypage-tab" class="hidden bg-white py-4 w-full border-l border-b border-r rounded-b-lg rounded-r-lg" data-tabs-target="panel">
                    <div class="w-11/12 mx-auto divide-y space-y-8 pb-8 px-4">
                        <div class="justify-start grid grid-flow-col gap-4 mt-10">
                            <div class="avatar">
                                <div class="w-24 rounded-full <%= user_rank(@user) %>-border">
                                    <% if @user.avatar.present? %>
                                        <%= image_tag @user.avatar.url %>
                                    <% else %>
                                        <%= image_tag("default.webp") %>
                                    <% end %>
                                </div>
                            </div>
                            <div class="mt-5">
                                <h2 class="text-xl font-zenmaru font-bold text-neutral flex items-center"><%= @user.name %></h2>
                                <div class="flex items-center">
                                    <div class="inline-block md:h-9 md:w-9 h-6 w-6">
                                        <%= image_tag(rank_icon(@user)) %>
                                    </div>
                                    <span class="text-xs text-secondary items-start font-semibold"><%= user_rank(@user) %>ランク<span>
                                    <button class="btn w-6 border-none rounded-full items-center" onclick="my_modal_2.showModal()"><i class="ph-bold ph-question fa-xl text-primary-hover"></i></button>
                                    <dialog id="my_modal_2" class="modal">
                                        <div class="modal-box">
                                            <%= image_tag("rank.webp") %>
                                        </div>
                                        <form method="dialog" class="modal-backdrop">
                                            <button>close</button>
                                        </form>
                                    </dialog>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex justify-center items-center w-screen md:mx-auto">
                        <div class="stats stats-vertical lg:stats-horizontal shadow-lg">   
                            <div class="stat">
                                <div class="stat-figure text-accent">
                                    <i class="ph-bold ph-seal-check fa-2x inline-block stroke-current"></i>
                                </div>
                                <div class="stat-title font-zenmaru font-semibold text-sm text-secondary">訪問済み数</div>
                                <div class="stat-value text-neutral"><%= @user.visits.count %></div>
                                <div class="stat-desc text-secondary">最近の訪問済：<%= @user.visits.present? ? @user.visits.last.created_at.strftime('%Y/%m/%d') : " - " %></div>
                            </div>
                            <div class="stat">
                                <div class="stat-figure text-accent">
                                    <i class="ph-bold ph-chat-circle-text fa-2x inline-block stroke-current"></i>
                                </div>
                                <div class="stat-title font-zenmaru font-semibold text-sm text-secondary">レビュー投稿数</div>
                                <div class="stat-value text-neutral"><%= @user.reviews.count %></div>
                                <div class="stat-desc text-secondary">最新のレビュー投稿：<%= @user.reviews.present? ? @user.reviews.last.created_at.strftime('%Y/%m/%d') : " - " %></div>
                            </div>
                            <div class="stat">
                                <div class="stat-figure text-accent">
                                    <i class="ph-bold ph-hand-heart fa-2x inline-block stroke-current"></i>
                                </div>
                                <div class="stat-title font-zenmaru font-semibold text-sm text-secondary">参考になった獲得数</div>
                                <div class="stat-value text-neutral"><%= @total_helpfuls %></div>
                                <div class="stat-desc text-secondary">最新の参考になった：<%= @user.reviews.joins(:helpfuls).present? ? @user.reviews.joins(:helpfuls).last.created_at.strftime('%Y/%m/%d') : " - " %></div>
                            </div>
                        </div>
                    </div>
                    <div class="w-full py-2 mt-8 origin-top-right bg-white dark:bg-gray-800 text-secondary">
                        <%= link_to visits_spots_path, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                            <p><i class="ph ph-seal-check fa-lg mr-1"></i> 訪問済み一覧</p>
                        <% end %>
                        <div class= "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" onclick="my_modal_3.showModal()" >
                            <p><i class="ph ph-pencil-simple fa-lg mr-1 fa-lg"></i> ユーザー情報編集</p>
                        </div>
                        <%= link_to terms_of_use_path, class: "md:hidden flex items-center p-3 text-sm capitalize transition-colors duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                            <p><i class="ph ph-file-text fa-lg mr-1"></i> 利用規約</p>
                        <% end %>
                        <%= link_to privacy_policy_path, class: "md:hidden flex items-center p-3 text-sm capitalize transition-colors duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                            <p><i class="ph ph-lock-key fa-lg mr-1"></i> プライバシーポリシー</p>
                        <% end %>
                        <%= link_to "https://twitter.com/819Chapchon", class: "md:hidden flex items-center p-3 text-sm capitalize transition-colors duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                            <p><i class="ph ph-envelope-simple fa-lg mr-1"></i> お問い合わせ</p>
                        <% end %>
                        <%= link_to destroy_user_session_path, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white", data: { turbo_method: :delete } do %>
                            <p><i class="ph ph-sign-out fa-lg mr-1"></i> ログアウト</p>
                        <% end %>
                        <dialog id="my_modal_3" class="modal">
                            <div class="modal-box">
                                <form method="dialog">
                                    <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
                                </form>
                                <%= render 'users/registrations/edit'%>
                            </div>
                        </dialog>
                    </div>
                </div>
                <div id="mypage-reviews-tab" class="hidden bg-white py-4 px-4 w-full border-l border-b border-r rounded-l-lg rounded-b-lg" data-tabs-target="panel">
                    <div class="w-11/12 mx-auto divide-y space-y-8 pb-8">
                        <h2 class="text-xl font-zenmaru font-bold text-neutral"><%= @user.name %>のレビュー一覧</h2>
                        <% if @reviews.present? %>
                            <%= render "users/reviews" %>
                            <%= paginate @reviews %>
                        <% else %>
                            <div class="mx-auto flex w-1/2 flex-col items-center mb-16 md:mb-0 gap-2.5 justify-center w-3/5">
                                <%= image_tag("936.webp", class: "h-64 w-56 flex items-center justify-center") %>
                                <h3 class="font-bold flex items-center justify-center w-full font-zenmaru text-neutral"> <i class="ph ph-empty fa-lg"></i>  まだ投稿がありません</h3>
                                <p class="text-sm flex items-center justify-center w-full text-secondary">レビューや猫スポットを投稿してさらに猫スポットを楽しもう！</p>
                                <%= link_to "#", class: "block w-full" do %>
                                    <button class="bg-accent text-white px-3 py-2 rounded-full flex mx-auto items-center justify-center w-full md:w-1/2">
                                        <p><i class="ph ph-chat-circle-dots fa-lg"></i> レビューを投稿する</p>
                                    </button>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <div>
</div>