config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  Sidekiq::Web.use(Rack::Auth::Basic) do |user_id, password|
    [user_id, password] == [ENV['SIDEKIQ_BASIC_ID'], ENV['SIDEKIQ_BASIC_PASSWORD']]
  end
  mount Sidekiq::Web, at: '/sidekiq'
  get 'rewiews/new'
  get 'rewiews/create'
  get 'users/show'
  root "static_pages#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/auth/failure' => 'omniauth_callbacks#failure'
  end
  get 'spot_images/:photo_reference', to: 'spot_images#show', as: 'spot_image_proxy'
  get 'static_pages/index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'spots/list', to: 'spots#list'
  get 'reviews/search', to: 'reviews#search'
  get 'proxy_image', to: 'spots#proxy_image'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['BUCKET_NAME']}/sitemaps/sitemap.xml.gz")
  resources :spots, only: %i[index show] do
    get 'tag_filter/:tag_id', to: 'spots#index', as: :tag_filter_reviews
    resources :reviews, only: %i[new create show edit update destroy]
    collection do
      get :bookmarks
      get :map
      get :search
      get :visits
    end
  end
  resources :screenshots, only: [:create] do
    collection do
      post :update_meta_tags
    end
  end
  resources :spot_bookmarks, only: %i[create destroy]
  resources :helpfuls, only: %i[create destroy]
  resources :visits, only: %i[create destroy]
  resources :tags, only: %i[] do
    collection do
      get :search
    end
  end
  resources :diagnostics, only: [] do
    member do
      get 'question', to: 'diagnostics#show_question', as: 'question'
      post 'answer_question', to: 'diagnostics#answer_question'
    end
    collection do
      get 'start', to: 'diagnostics#start'
      get 'result', to: 'diagnostics#result'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.html.erb
<div class="hidden md:block md:fixed md:top-0 md:left-0 md:z-10 w-full" data-controller="login-modal">
  <div class="navbar bg-primary text-secondary ">
    <div class="flex-1">
      <%= link_to 'NekoSpot', map_spots_path, data: { turbo: false }, class: "btn btn-ghost text-xl" %>
    </div>
    <div class="flex-none" >
      <button type="button" data-action="click->login-modal#openModal" class="btn items-center justify-center h-full border-none px-4 hover:bg-gray-50 group">
        <i class="ph ph-sign-in fa-2xl text-secondary group-hover:text-neutral" aria-hidden="true"></i>
      </button>
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn m-1 border-none"><i class="ph ph-list fa-2xl"></i></div>
          <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-primary w-56 rounded-box">
            <li>
              <%= link_to map_spots_path, data: { turbo: false }, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform text-neutral dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                  <p><i class="ph-bold ph-magnifying-glass w-5 h-5 mb-2 font-semibold text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;検索</p>
              <% end %>
            </li>
            <li>
              <%= link_to spots_path, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform text-neutral dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                  <p><i class="ph-bold ph-list-dashes fa-lg w-5 h-4 mt-2 font-semibold text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;一覧</p>
              <% end %>
            </li>
            <li>
              <%= link_to start_diagnostics_path, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform text-neutral dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                  <p><i class="ph-fill ph-paw-print fa-lg w-5 h-4 mt-2 font-semibold text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;診断</p>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <%= render 'shared/login_modal' %>
    </div>
  </div>
</div>

<div class="fixed bottom-0 left-0 z-50 w-full h-16 bg-primary border-t border-primary-hover md:hidden" data-controller="login-modal">
    <div class="grid h-full max-w-lg grid-cols-4 mx-auto font-medium" >
        <%= link_to map_spots_path, data: { turbo: false }, class: "inline-flex mt-2 flex-col items-center justify-start px-2 group" do %>
            <i class="ph-bold ph-magnifying-glass fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral">検索</span>
        <% end %>
        <%= link_to spots_path, class: "inline-flex flex-col items-center justify-start mt-2 px-2 group" do %>
            <i class="ph-bold ph-list-dashes fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral">一覧</span>
        <% end %>
        <%= link_to start_diagnostics_path, class: "inline-flex mt-2 flex-col items-center justify-start px-2 group" do %>
            <i class="ph-fill ph-paw-print fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary group-hover:text-neutral">診断</span>
        <% end %>
        <button type="button" data-action="click->login-modal#openModal" class="inline-flex mt-2 flex-col items-center justify-start px-2 group">
            <i class="ph-bold ph-sign-in fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral">ログイン</span>
        </button>
    </div>
    <%= render 'shared/login_modal' %>
</div>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="bg-red-100 text-sm text-red-700 px-3 py-3 mb-5 rounded-xl relative">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li class="py-1"><i class="ph-fill ph-paw-print"></i> <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if controller_name == 'static_pages' && action_name == 'index' %>
  <!-- TOPページではフッターが常に表示される -->
  <%= render "shared/footer_contents" %>
<% elsif !(controller_name == 'reviews' && action_name == 'search') && !(controller_name == 'spots' && action_name == 'search') %>
  <!-- reviews/search と spots/search 以外では -->
  <% unless controller_name == 'spots' && action_name == 'map' %>
    <!-- PC画面ではspots/map以外でフッターが表示される -->
    <div class="<%= 'hidden md:block' %>">
      <%= render "shared/footer_contents" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer_contents.html.erb
<div class="footer footer-center p-10 bg-primary text-secondary rounded items-end w-screen">
    <nav class="grid grid-flow-col gap-4">
        <%= link_to '利用規約', terms_of_use_path %>
        <%= link_to 'プライバシー・ポリシー', privacy_policy_path %>
        <%= link_to 'お問い合わせ', 'https://twitter.com/819Chapchon', target: '_blank', rel: 'noopener noreferrer' %>
    </nav>
    <aside>
        <p>Copyright © 2024</p>
    </aside>
</div>

app/views/shared/_header.html.erb
<nav class="hidden md:block md:fixed md:top-0 md:left-0 md:z-[100] w-full">
    <div class="navbar bg-primary text-secondary">
        <div class="flex-1">
            <%= link_to 'NekoSpot', map_spots_path, class: "btn btn-ghost text-xl" %>
        </div>
        <div class="flex-none">
            <div class="dropdown dropdown-end">
                <div tabindex="0" role="button" class="btn m-1 border-none"><i class="ph ph-list fa-2xl"></i></div>
                    <ul tabindex="0" class="dropdown-content z-[100] menu p-2 shadow bg-primary w-56 rounded-box">
                        <li>
                            <%= link_to map_spots_path, data: { turbo: false }, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 text-neutral dark:hover:text-white" do %>
                                <p><i class="ph-bold ph-magnifying-glass w-5 h-5 mb-2 text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;マップ検索</p>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to spots_path, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 text-neutral transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                                <p><i class="ph-bold ph-list-dashes fa-lg w-5 h-4 mt-2 font-semibold text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;一覧検索</p>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to start_diagnostics_path, class: "flex items-center p-3 text-sm capitalize transition-colors text-neutral duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                                <p><i class="ph-fill ph-paw-print fa-lg w-5 h-4 mt-2 font-semibold text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;猫スポット診断</p>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to bookmarks_spots_path, class: "flex items-center p-3 text-sm capitalize transition-colors text-neutral duration-300 transform dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                                <p><i class="ph-bold ph-heart fa-lg w-5 h-4 mt-2 font-semibold text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;お気に入り / 訪問済</p>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to users_show_path(current_user), class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform text-neutral dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white" do %>
                                <p><i class="ph-bold ph-user-circle fa-lg w-5 h-4 mt-2 font-semibold text-neutral group-hover:text-secondary" aria-hidden="true"></i>&emsp;Myページ</p>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to destroy_user_session_path, class: "flex items-center p-3 text-sm capitalize transition-colors duration-300 transform text-neutral dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white", data: { turbo_method: :delete } do %>
                                <p><i class="ph-bold ph-sign-out fa-lg mr-1 font-semibold text-neutral group-hover:text-secondary"></i> ログアウト</p>
                            <% end %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="fixed bottom-0 left-0 z-50 w-full h-16 bg-primary border-t border-primary-hover md:hidden">
    <div class="grid h-full max-w-lg grid-cols-5 mx-auto font-medium">
        <%= link_to map_spots_path, data: { turbo: false }, class: "inline-flex flex-col items-center justify-start mt-2 px-2 group" do %>
            <i class="ph-bold ph-magnifying-glass fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral">検索</span>
        <% end %>
        <%= link_to spots_path, class: "inline-flex flex-col items-center justify-start mt-2 px-2 group" do %>
            <i class="ph-bold ph-list-dashes fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral">一覧</span>
        <% end %>
        <%= link_to start_diagnostics_path, class: "inline-flex flex-col items-center justify-start mt-2 px-2 group" do %>
        <i class="ph-fill ph-paw-print fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary group-hover:text-neutral">診断</span>
        <% end %>
        <%= link_to bookmarks_spots_path, method: :get, class: "inline-flex flex-col items-center justify-start mt-2 px-1 group" do %>
            <i class="ph-bold ph-heart fa-lg w-6 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral">保存/訪問済</span>
        <% end %>
        <%= link_to users_show_path(current_user), method: :get, class: "inline-flex flex-col items-center justify-start mt-2 px-2 group" do %>
            <i class="ph-bold ph-user-circle fa-lg w-5 h-4 mt-2 text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <span class="text-[9px] text-secondary dark:text-gray-400 group-hover:text-neutral">Myページ</span>
        <% end %>
    </div>
</div>

app/views/shared/_login_modal.html.erb
<div class="hidden fixed inset-0 flex items-center justify-center z-50 bg-gray-500 bg-opacity-50" data-login-modal-target="backGround">
  <dialog data-login-modal-target="dialog" class="hidden relative rounded-xl shadow-lg p-10 flex flex-col justify-center w-full md:w-3/5">
    <button type="button" data-action="click->login-modal#closeModal" class="absolute top-3 right-4">
      <i class="ph ph-x h-6 w-6 text-secondary"></i>
    </button>
      <div class="mx-auto flex flex-col justify-center items-center w-full">
        <%= image_tag("512.webp", class: "w-3/5") %>
        <h3 class="font-bold flex items-center justify-center w-full font-zenmaru text-neutral"> <i class="ph ph-sign-in fa-lg"></i>  ログインして続ける</h3>
        <p class="flex items-center justify-center w-full font-zenmaru text-secondary text-xs pt-2">▼ ログインすると使える機能</p>
        <div class="text-xs text-secondary flex items-center justify-center w-full">
          <ul class="py-2">
          <li><i class="ph ph-bookmark-simple fa-lg"></i> お気に入り</li>
          <li><i class="ph ph-chat-circle-dots fa-lg"></i> 口コミ投稿</li>
          <li><i class="ph ph-medal fa-lg"></i> 訪問済み機能</li>
          </ul>
        </div>
        <div class="flex-col items-center justify-center w-full space-y-2 mb-8 mt-4">
        <%= link_to user_line_omniauth_authorize_path, class: "flex items-center justify-center w-full", method: :post, data: { turbo: false } do %>
          <button class="bg-line-base text-white hover:bg-line-hover px-3 py-1.5 rounded-full flex items-center justify-center w-full md:w-4/5 text-sm">
          <%= image_tag("line_64.png", alt: "Logo", class: "h-10 mr-4 ") %>
            LINEでログイン
          </button>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <% end %>
        <%= link_to user_google_oauth2_omniauth_authorize_path, class: "flex items-center justify-center w-full", method: :post, data: { turbo: false } do %>
          <button class="bg-white text-google-text hover:bg-google-hover px-4 py-2 border border-google rounded-full flex items-center w-full justify-center md:w-4/5 text-sm">
          <%= image_tag("g-logo.png", alt: "Logo", class: "h-8 mr-4 ") %>
          Googleでログイン
          </button>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <% end %>
        </div>
      </div>
    </div>
  </dialog>
  </div>

app/views/shared/_search.html.erb
<div data-controller="autocomplete" data-autocomplete-url-value="/spots/search" role="combobox">
    <%= search_form_for @q, url: url, html: { id: "searchForm", class: "mx-auto md:w-11/12 w-11/12 md:mx-6 pt-6" }, remote: true  do |f| %>
        <label for="" class="mb-2 text-sm font-medium text-secondary sr-only dark:text-white">検索</label>
        <div class="relative">
            <div class="absolute inset-y-4 start-0 flexed items-center ps-3 pointer-events-none">
                <i class="ph ph-magnifying-glass text-secondary"></i>
            </div>
            <%= f.search_field :name_or_address_cont, data: { autocomplete_target: 'input' }, class: 'block w-full md:11/12 p-4 ps-8 text-xs text-secondary border border-secondary rounded-full bg-white focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder: '猫スポット名 or 住所' %>
            <%= f.hidden_field :name, data: { autocomplete_target: 'hidden' } %>
            <%= f.hidden_field :address, data: { autocomplete_target: 'hidden' } %>
            <%= f.submit '検索', class: 'hidden md:block text-white absolute fixed inset-y-2 end-2 py-2 h-9 bg-accent hover:bg-accent-hover focus:ring-4 focus:outline-none focus:ring-primary font-medium rounded-full text-sm px-4 py-0.5' %>
            <ul class="list-group absolute w-full bg-white p-2 shadow z-[1] rounded-box" data-autocomplete-target="results"></ul>
        </div>
        <div class="md:flex flex-col md:flex-row md:pt-4 pt-8 pl-8 md:p-8 text-secondary justify-start items-center md:w-1/2">
            <div class='label-select flex h-full text-sm space-x-2 items-center'>
                <%= f.check_box :foster_parents_eq, { include_hidden: false, class: 'search-select text-sm checkbox checkbox-sm checkbox-secondary [--chkbg:theme(colors.secondary)] [--chkfg:white]' }, 1, nil %>
                <%= f.label :foster_parents_eq, '里親募集あり', class: 'label text-sm font-semibold' %>
            </div>
            <div class='md:px-8 label-select flex h-full text-sm space-x-2 items-center'>
                <%= f.check_box :adoption_event_eq, { include_hidden: false, class: 'search-select text-sm checkbox checkbox-sm checkbox-secondary [--chkbg:theme(colors.secondary)] [--chkfg:white]' }, 1, nil %>
                <%= f.label :adoption_event_eq, '譲渡会開催実績あり', class: 'label text-sm font-semibold' %>
            </div>
        </div>
        <div class="md:flex">
            <div class="space-x-2 mt-8 mx-4 md:mt-0 md:mx-0 md:w-1/2">
                <h3 class="text-secondary font-semibold">カテゴリーから検索</h3>
                <div id="category-buttons" class="flex flex-wrap gap-2 p-4">
                    <label class="bg-primary text-sm text-secondary px-2 py-1.5 rounded-full hover:bg-primary-dark cursor-pointer">
                        <%= f.radio_button :category_id_eq, '', checked: true, class: 'hidden', id: 'category_all' %>
                        すべて
                    </label>
                    <% @categories.all.each do |category| %>
                        <label class="bg-primary text-sm text-secondary px-2 py-1.5 rounded-full hover:bg-primary-dark cursor-pointer" data-category-id="<%= category.id %>">
                            <%= f.radio_button :category_id_eq, category.id, class: 'hidden', id: "category_#{category.id}" %>
                            <%= category.name %>
                        </label>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="md:flex">
            <div class="space-x-2 mt-8 mx-4 md:mt-4 md:mx-0 md:w-1/2" data-controller="radio-tags">
                <h3 class="md:mt-4 md:mb-3 text-secondary font-semibold">タグから検索</h3>
                <div class="flex flex-wrap gap-2 p-4">
                    <div class="my-1 inline-flex text-secondary text-sm rounded-full py-1.5 px-2 bg-primary items-center hover:bg-primary-hover" data-radio-tags-target="tag" data-action="click->radio-tags#select">
                        <%= f.radio_button :with_tag, '', id: "tag_none", checked: true, class: 'hidden' %>
                        <%= f.label :with_tag, "指定なし", value: '', for: "tag_none" %>
                    </div>
                    <% @tags.each do |tag| %>
                        <div class="my-1 group inline-flex text-secondary text-sm rounded-full py-1.5 px-2 bg-primary items-center hover:bg-primary-hover" data-radio-tags-target="tag" data-action="click->radio-tags#select">
                            <%= f.radio_button :with_tag, tag.name, id: "tag_#{tag.id}", class: 'hidden' %>
                            <i class="ph ph-tag"></i>&nbsp;<%= f.label :with_tag, tag.name, for: "tag_#{tag.id}" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="md:hidden fixed bottom-4 right-3 flex justify-center items-center z-30">
            <%= button_tag type: 'submit', class: 'font-semibold text-sm rounded-full relative inline-flex group items-center justify-center px-5 py-3 m-1 cursor-pointer border-b-4 border-l-2 active:border-accent active:shadow-none shadow-lg bg-gradient-to-tr from-accent to-accent-active border-accent-hover text-white' do %>
                <span class="absolute w-0 h-0 transition-all duration-300 ease-out bg-white rounded-full group-hover:w-32 group-hover:h-32 opacity-10"></span>
                <span class="relative"><i class="ph-bold ph-magnifying-glass fa-2xl"></i><br><span class="text-[14px]">検索</span></span>
            <% end %>
        </div>
    <% end %>
</div>

app/views/shared/_spot_show_header.html.erb
<div class="fixed bottom-16 left-0 z-30 w-full h-16 bg-white bg-opacity-65 border-primary-hover md:hidden" data-controller="modal login-modal">
  <div class="grid h-full max-w-lg grid-cols-5 mx-auto font-medium">
      <% if user_signed_in? %>
      <%= link_to new_spot_review_path(@spot), class: "btn text-white text-[16px] ml-4 drop-shadow-md my-2 inline-flex flex-col col-span-4 items-center justify-center px-4 rounded-md bg-accent hover:bg-accent-hover hover:shadow-lg", data: { turbo_frame: 'review_modal' } do %>
        <p><i class="ph ph-chat-circle-dots fa-lg"></i> 口コミを投稿する</p>
      <% end %>
      <% else %>
        <button data-action="click->login-modal#openModal" class="btn text-white text-[16px] ml-4 drop-shadow-md my-2 inline-flex flex-col col-span-4 items-center justify-center px-4 rounded-md bg-accent hover:bg-accent-hover hover:shadow-lg" >
        <p><i class="ph ph-chat-circle-dots fa-lg"></i> 口コミを投稿する</p>
      </button>
      <% end %>
      <div class="inline-flex flex-col items-center justify-center text-secondary col-span-1">
      <%= render 'bookmark_buttons', { spot: @spot } %>
      </div>
  </div>
  <%= render 'shared/login_modal' %>
</div>