config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  Sidekiq::Web.use(Rack::Auth::Basic) do |user_id, password|
    [user_id, password] == [ENV['SIDEKIQ_BASIC_ID'], ENV['SIDEKIQ_BASIC_PASSWORD']]
  end
  mount Sidekiq::Web, at: '/sidekiq'
  get 'rewiews/new'
  get 'rewiews/create'
  get 'users/show'
  root "static_pages#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/auth/failure' => 'omniauth_callbacks#failure'
  end
  get 'spot_images/:photo_reference', to: 'spot_images#show', as: 'spot_image_proxy'
  get 'static_pages/index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'spots/list', to: 'spots#list'
  get 'reviews/search', to: 'reviews#search'
  get 'proxy_image', to: 'spots#proxy_image'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['BUCKET_NAME']}/sitemaps/sitemap.xml.gz")
  resources :spots, only: %i[index show] do
    get 'tag_filter/:tag_id', to: 'spots#index', as: :tag_filter_reviews
    resources :reviews, only: %i[new create show edit update destroy]
    collection do
      get :bookmarks
      get :map
      get :search
      get :visits
    end
  end
  resources :screenshots, only: [:create] do
    collection do
      post :update_meta_tags
    end
  end
  resources :spot_bookmarks, only: %i[create destroy]
  resources :helpfuls, only: %i[create destroy]
  resources :visits, only: %i[create destroy]
  resources :tags, only: %i[] do
    collection do
      get :search
    end
  end
  resources :diagnostics, only: [] do
    member do
      get 'question', to: 'diagnostics#show_question', as: 'question'
      post 'answer_question', to: 'diagnostics#answer_question'
    end
    collection do
      get 'start', to: 'diagnostics#start'
      get 'result', to: 'diagnostics#result'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  has_many :helpfuls, dependent: :destroy
  has_many :review_tags, dependent: :destroy
  has_many :tags, through: :review_tags
  attr_accessor :images_cache, :tag_names
  mount_uploaders :images, ImageUploader




  validates :rating, presence: true, numericality: { in: 1..5, message: "を入力してください" }
  validates :body, length: { maximum: 400 }
  validate :validate_image_count
  validate :validate_tag_count
  #validate :validate_images

  after_save :log_review_save

  def log_review_save
    Rails.logger.debug "Review saved with images: #{images.inspect}"
  end

  # 画像削除を処理するメソッド
  def remove_image_at_index(index)
    remain_images = self.images # 現在の画像を複製
    remain_images.delete_at(index)
    self.images = remain_images
  end

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "id_value", "rating", "spot_id", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["spot", "user"]
  end

  def save_tags(tag_list)
    if tag_list.size > 5
      errors.add(:tags, "タグは5件までです。")
      return false
    end

    self.tags.clear
    tag_list.each do |new_name|
      review_tag = Tag.find_or_create_by(name: new_name)
      self.tags << review_tag
    end
  end

  # レビューの文字数を判定
  def long_body?(length = 10)
    body.length > length
  end

  # タグに基づいたレビューをフィルタリングするスコープ
  scope :review_tag, ->(tag_id) { joins(:tags).where(tags: { id: tag_id }) }

  private

  def validate_image_count
    if images.size > 3
      errors.add(:images, "画像のアップロードは３枚までです。")
    end
  end

  def validate_tag_count
    if tags.size > 5
      errors.add(:tags, "タグは5件までです。")
    end
  end


=begin %>
  def validate_images
    return if images.blank? || images.all?(&:blank?)

    cleaned_images = images.reject(&:blank?)
    inappropriate_images = []

    cleaned_images.each do |image|
      result = Vision.image_analysis(image)
      inappropriate_images << image unless result
    end

    if inappropriate_images.any?
      errors.add(:images, '不適切な画像が含まれています')
    end
  end
  <%
=end
end

app/controllers/reviews_controller.rb
require 'aws-sdk-s3'

class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_spot, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build(review_params)
    tag_list = extract_tag_list(params[:review][:tag_ids])

    if tag_list.size > 5
      @review.errors.add(:tags, "タグは5件までです。")
      reviews_data
      render :new, status: :unprocessable_entity
    elsif @review.save
      @review.save_tags(tag_list)
      reviews_data
      flash.now[:success] = "口コミを投稿しました"
      render turbo_stream: [
        turbo_stream.prepend("reviews", partial: "reviews/review", locals: { review: @review }),
        turbo_stream.replace("average_rating", partial: "spots/average_rating"),
        turbo_stream.replace("reviews_count", partial: "spots/reviews_count"),
        turbo_stream.replace("review_tab", partial: "spots/review_tab"),
        turbo_stream.update("flash", partial: "layouts/flash_messages"),
        turbo_stream.replace("no_reviews", partial: "reviews/review_list", locals: { spot: @review.spot })
      ]
    else
      reviews_data
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @tag_list = @review.review_tags.joins(:tag).pluck('tags.name').join(', ')
  end

  def update
    # 現在のレビューに関連付けられている画像をexisting_imagesに保持
    existing_images = @review.images

    # review_paramsからspot_idとimagesを除いた属性を@reviewに割り当て
    @review.assign_attributes(review_params.except(:spot_id, :images))

    # 新しい画像が存在する場合、既存の画像に追加。存在しない場合は、元の画像を保持する。
    if review_params[:images].present?
      @review.images += review_params[:images]
    else
      @review.images = existing_images
    end

    # 削除する画像のインデックスが指定されている場合、その画像を削除する。インデックスはカンマで分割。
    if params[:review][:remove_image_at].present?
      params[:review][:remove_image_at].split(',').each do |index|
        @review.remove_image_at_index(index.to_i)
      end
    end

    tag_list = extract_tag_list(params[:review][:tag_ids])
    uploaded_images = params[:review][:uploaded_images]

    # 画像のバリデーションが成功し、レビューが保存できた場合
    if tag_list.size > 5
      @review.errors.add(:tags, "タグは5件までです。")
      reviews_data
      render :edit, status: :unprocessable_entity
    elsif @review.save
      reviews_data #レビューに関連するデータを更新し
      @review.save_tags(tag_list) #タグを保存する。
      flash.now[:success] = "口コミを更新しました"
      render turbo_stream: [
        turbo_stream.replace(@review),
        turbo_stream.replace("average_rating", partial: "spots/average_rating"),
        turbo_stream.update("flash", partial: "layouts/flash_messages")
      ]
    else
      reviews_data
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @review.destroy!
    reviews_data
    flash.now[:success] = "口コミを削除しました"
    render turbo_stream: [
      turbo_stream.remove(@review),
      turbo_stream.replace("average_rating", partial: "spots/average_rating"),
      turbo_stream.replace("reviews_count", partial: "spots/reviews_count"),
      turbo_stream.replace("review_tab", partial: "spots/review_tab"),
      turbo_stream.update("flash", partial: "layouts/flash_messages"),
      (@review.spot.reviews.count.zero? ? turbo_stream.replace("reviews_list", partial: "spots/no_reviews") : nil)
    ].compact,status: :see_other
  end

  def search
    query = params[:q]
    if query.present?
      @reviews = Review.ransack(spot_name_or_spot_address_or_body_cont: query).result
      @search_by_spot_name = Review.ransack(spot_name_cont: query).result.exists?
      @search_by_spot_address = Review.ransack(spot_address_cont: query).result.exists?
      @search_by_body = Review.ransack(body_cont: query).result.exists?
    else
      @reviews = Review.none
      @search_by_spot_name = false
      @search_by_spot_address = false
      @search_by_body = false
    end

    respond_to do |format|
      format.html # For normal HTML requests
      format.json # For AJAX requests
    end
  end

  def show
    review = Review.last
    @user = review.user if review.present?
    @review = Review.find(params[:id])
    @reviews = @user.reviews.includes(:spot)
    
    if @review.images.present?
      # 最初の画像ファイル名を取得
      first_image_file_name = @review.images.first

      # 最初の画像ファイル名を取得
      first_image_file_name = @review.images.first.identifier
      # アップローダーインスタンスを作成し、最初の画像ファイルをストレージから取得
      image_uploader = ImageUploader.new(@review, :images)
      image_uploader.retrieve_from_store!(first_image_file_name)
      # OGPバージョンのURLを取得
      @first_ogp_image_url = image_uploader.ogp.url
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body, { images: [] }, :images_cache).merge(spot_id: params[:spot_id])
  end

  def set_spot
    @spot = Spot.find(params[:spot_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def reviews_data
    @reviews = @spot.reviews.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
    @average_rating = @spot.reviews.average(:rating).to_f
    @all_reviews_count = @spot.reviews.count
  end

  def extract_tag_list(tag_ids_param)
    tag_ids_param.first.present? ? JSON.parse(tag_ids_param.first).map { |tag| tag["value"] } : []
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_crud_menus.html.erb
<%= button_to edit_spot_review_path(@spot, review), method: :get, data: { turbo_frame: 'review_modal' } do %>
    <i class="ph-fill ph-note-pencil fa-lg text-secondary text-sm drop-shadow-md rounded-lg"></i>
<% end %>
<%= button_to spot_review_path(@spot, review), method: :delete, data: { turbo_confirm: "本当に削除しますか？" } do %>
    <i class="ph-fill ph-trash fa-lg text-secondary text-sm drop-shadow-md rounded-lg"></i>
<% end %>

app/views/reviews/_helpful.html.erb
<%= link_to helpfuls_path(review_id: review.id), id: "helpful-button-for-review-#{review.id}", data: { turbo_method: :post }, class: "w-32 bg-primary text-secondary text-sm px-2 drop-shadow-md hover:shadow-none py-2 rounded-lg flex mx-auto items-center justify-center" do %>
    <p><i class="ph ph-fill ph-hand-heart fa-lg"></i> 参考になった <span class="px-2 py-1.5 rounded-full bg-white text-secondary text-[9px]"><%= review.helpfuls.count %></span></p>
<% end %>

app/views/reviews/_helpful_buttons.html.erb
<% if user_signed_in? %>
    <div class='mx-auto'>
        <% if current_user.helpful?(review) %>
            <%= render 'reviews/unhelpful', { review: review } %>
        <% else %>
            <%= render 'reviews/helpful', { review: review } %>
        <% end %>
    </div>
<% else %>
<div class='mx-auto'>
    <button data-action="click->login-modal#openModal" class="bg-primary text-secondary text-sm px-3 drop-shadow-md py-2 rounded-lg flex mx-auto items-center justify-center">
        <p><i class="ph ph-fill ph-hand-heart fa-lg"></i> 参考になった <span class="px-2 py-1.5 rounded-full bg-white text-secondary text-[9px]"><%= review.helpfuls.count %></span></p>
    </button>
    <%= render 'shared/login_modal' %>
</div>
<% end %>

app/views/reviews/_review.html.erb
<%= turbo_frame_tag dom_id(review) do %>
  <div class="flex flex-col gap-3 px-4 py-6 md:p-6 space-y-2" data-controller="image-modal">
    <div class="flex w-full justify-between">
      <div class="flex items-center">
        <div>
          <% if review.user.avatar.present? %>
            <%= image_tag review.user.avatar.url, class: "inline-block rounded-full h-9 w-9" %>
          <% else %>
            <%= image_tag("default.png", class: "inline-block rounded-full h-9 w-9") %>
          <% end %>
        </div>
        <div class="ml-3">
          <span class="block text-sm text-neutral"><%= review.user.name %></span>
          <span class="block text-xs text-secondary"><%= review.created_at.strftime('%Y/%m/%d') %></span>
        </div>
      </div>
      <div class="flex space-x-2 items-center">
        <% if review.user == current_user %>
          <%= render 'reviews/crud_menus', review: review %>
        <% end %>
      </div>
    </div>
    <div class="-ml-1 flex gap-0.5">  
      <% rating = review.rating %>
      <% full_stars = rating %>
      <% empty_stars = 5 - rating %>
      <% full_stars.times do %>
        <i class="ph-fill ph-star fa-lg text-yellow-400"></i>
      <% end %>
      <% empty_stars.times do %>
        <i class="ph-fill ph-star fa-lg text-gray-100"></i>
      <% end %>
    </div>
    <p class="text-secondary"><%= review.body %></p>
    <div class="flex space-x-2">
      <% if review.tags.present? %>
        <% review.tags.each do |tag| %>
          <%= link_to spot_path(@spot, tag_id: tag.id), data: { turbo_frame: "tags_search" }, class: "inline-flex text-secondary text-xs rounded-lg py-1.5 px-2 bg-primary items-center hover:bg-primary-hover" do %>
              <i class="ph ph-tag"></i>&nbsp;<%= tag.name %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <% if review.images.present? %>
      <div class="flex space-x-2">
        <% review.images.each do |image| %>
          <%= image_tag image.to_s, data: { action: "click->image-modal#open", image_url: image.url }, class: "inline-block rounded h-16 w-16" %>
        <% end %>
      </div>
    <% end %>
          <div class="h-full justify-end mx-auto flex flex-col">
        <div class="w-full flex flex-row mx-auto space-y-2 pt-2 md:space-x-2 space-x-4">
            <% unless review.user == current_user %>
                <% if user_signed_in? %>
                    <div class='mx-auto'>
                        <% if current_user.helpful?(review) %>
                            <%= render 'reviews/unhelpful', { review: review } %>
                        <% else %>
                            <%= render 'reviews/helpful', { review: review } %>
                        <% end %>
                    </div>
                <% else %>
                    <div class='mx-auto'>
                        <button data-action="click->login-modal#openModal" class="bg-primary text-secondary  px-3 drop-shadow-md py-2 rounded-lg flex mx-auto items-center justify-center">
                            <p class="text-sm"><i class="ph ph-fill ph-hand-heart fa-lg"></i> 参考になった <span class="px-2 py-1.5 rounded-full bg-white text-secondary text-[9px]"><%= review.helpfuls.count %></span></p>
                        </button>
                    </div>
                <% end %>
            <% end %>
            <div>
                <%= link_to "https://x.com/intent/tweet?u/intent/tweet?url=https://nekospot.jp/spots/#{review.spot.id}/reviews/#{review.id}&text=#{ERB::Util.url_encode("「#{review.spot.name}」の口コミを投稿しました🐈✨\n ##{review.spot.name.gsub(/[\s()（）【】]/, '')} #NekoSpot \n")}", target: '_blank', class: "relative rounded md:px-3 py-2.5 px-2 overflow-hidden group bg-neutral relative hover:bg-gradient-to-r hover:from-neutral hover:to-secondary text-white hover:ring-2 hover:ring-offset-2 hover:ring-secondary transition-all ease-out duration-300" do %>
                        <span class="absolute right-0 w-8 h-32 -mt-12 transition-all duration-1000 transform translate-x-12 bg-white opacity-10 rotate-12 group-hover:-translate-x-40 ease"></span>
                        <span class="relative text-sm text-white dark:text-gray-400 "><i class="ph-bold ph-x-logo fa-lg w-6 h-3" aria-hidden="true"></i>シェア</span>
                <% end %>
            </div>
        </div>
    </div>

    <!-- モーダル -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-50 hidden z-50" data-image-modal-target="imageModal">
      <div class="fixed inset-0 flex items-center justify-center z-100">
        <% if review.images.length == 1 %>
          <div class="rounded shadow-md relative">
            <img data-image-modal-target="image" class="w-screen md:max-w-96 max-h-96"/>
            <button data-action="click->image-modal#close" class="absolute top-3 right-4 m-4 text-secondary rounded-full bg-white shadow-md px-2 py-1 items-center">
              <i class="ph-bold ph-x text-secondary"></i>
            </button>
          </div>
        <% else %>
          <div class="bg-white p-4 rounded shadow-md relative flex items-center">
            <button data-action="click->image-modal#prev" class="absolute left-0 top-1/2 transform -translate-y-1/2 p-2 text-primary text-3xl bg-opacity-50 rounded-full">
              <i class="ph-bold ph-caret-left fa-2xl"></i>
            </button>
            <div class="carousel transition duration-700 ease-in-out" data-image-modal-target="carousel">
              <% review.images.each_with_index do |image, index| %>
                <img src="<%= image.url %>" class="max-w-96 max-h-96 <%= index == 0 ? 'block' : 'hidden' %>" data-image-modal-target="carouselImage"/>
              <% end %>
            </div>
            <div class="absolute bottom-8 left-1/2 transform -translate-x-1/2 flex space-x-2 mt-4" data-image-modal-target="indicators">
              <% review.images.each_with_index do |image, index| %>
                <div class="indicator w-3 h-3 rounded-full <%= index == 0 ? 'bg-secondary' : 'bg-primary' %>" data-image-modal-target="indicator" data-action="click->image-modal#indicatorClick" data-index="<%= index %>"></div>
              <% end %>
            </div>
            <button data-action="click->image-modal#next" class="absolute right-0 top-1/2 transform -translate-y-1/2 p-2 text-primary text-3xl bg-opacity-50 rounded-full">
              <i class="ph-bold ph-caret-right fa-2xl"></i>
            </button>
            <button data-action="click->image-modal#close" class="absolute top-4 right-6 m-4 text-secondary rounded-full bg-white shadow-md px-2 py-1 items-center">
              <i class="ph-bold ph-x h-6 w-6 text-secondary"></i>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/reviews/_unhelpful.html.erb
<%= link_to helpful_path(current_user. helpfuls.find_by(review_id: review.id)), id: "unhelpful-button-for-review-#{review.id}", data: { turbo_method: :delete }, class: "w-32 bg-primary text-secondary text-sm px-2 py-2 rounded-lg flex mx-auto items-center justify-center group" do %>
    <p><i class="ph ph-fill ph-hand-heart fa-lg items-center"></i> 参考になった <span class="px-2 py-1.5 rounded-full bg-white text-secondary text-[9px]"><%= review.helpfuls.count %></span></p>
<% end %>

app/views/reviews/show.html.erb
<% assign_meta_tags title: @review.spot.name, image: @first_ogp_image_url %>
<div id="flash">
<%= render 'layouts/flash_messages', flash: flash %>
</div>
<nav class="md:hidden w-full h-12 ">
    <div class="navbar bg-primary text-secondary border-b border-primary-hover">
        <div class="flex-1 items-center mb-3">
            <%= link_to "", class: "back-link", data: { turbo: false, excluded_paths: [user_line_omniauth_authorize_path, user_google_oauth2_omniauth_authorize_path].to_json } do %>
                <i class="ph-light ph-caret-left fa-2xl text-secondary group-hover:text-neutral" aria-hidden="true"></i>
            <% end %>
        </div>
    </div>
</nav>
<section class="md:mt-32 ">
    <div class="py-12 mx-auto max-w-7xl md:px-12 lg:px-24 lg:py-24 h-screen items-center">
        <div class="flex flex-wrap items-center mx-auto max-w-7xl">
            <div class="w-full lg:max-w-lg lg:w-1/2 md:rounded-xl">
                <div>
                    <% if @review.images.present? %>
                        <div class="relative w-full max-w-lg">
                            <div class="absolute top-0 rounded-full bg-accent -left-4 w-72 h-72 mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
                            <div class="absolute rounded-full bg-accent-active -bottom-24 right-20 w-72 h-72 mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
                            <div class="relative">
                                <div class="swiper w-screen md:w-96 h-96 md:rounded-md">
                                <!-- Additional required wrapper -->
                                    <div class="swiper-wrapper">
                                        <!-- Slides -->
                                        <% @review.images.each do |image| %>
                                            <div class="swiper-slide"><%= image_tag image.to_s %></div>
                                        <% end %>
                                    </div>
                                    <!-- If we need pagination -->
                                    <div class="swiper-pagination"></div>
                                    <!-- If we need navigation buttons -->
                                    <div class="swiper-button-prev"></div>
                                    <div class="swiper-button-next"></div>
                                    <!-- If we need scrollbar -->
                                    <div class="swiper-scrollbar"></div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="px-4 flex flex-col items-start mt-12 mb-16 text-left lg:flex-grow lg:w-1/2 lg:pl-6 xl:pl-24 md:mb-0 xl:mt-0">
                <%= link_to spot_path(@review.spot), data: { turbo: false }, class: "mb-8 font-bold flex items-center justify-start w-full font-zenmaru text-sm text-neutral whitespace-pre-wrap hover:text-secondary" do %>
                    <span><i class="ph-fill ph-map-pin fa-lg inline-block"></i></span>&nbsp;<%= @review.spot.name %>
                <% end %>
                <div class="flex w-full justify-between">
                    <div class="flex items-center">
                        <div class="avatar">
                            <div class="w-20 rounded-full <%= user_rank(@user) %>-border">
                                <% if @review.user.avatar.present? %>
                                    <%= image_tag @review.user.avatar.url %>
                                <% else %>
                                    <%= image_tag("default.webp") %>
                                <% end %>
                            </div>
                        </div>
                        <div class="md:ml-2 px-4">
                            <div class="inline-block text-sm text-neutral"><%= @review.user.name %></div>                    
                                <div class="inline-block h-6 w-6 items-center pt-2">
                                    <%= image_tag(rank_icon(@user)) %>
                                </div>
                            <div class="block text-xs text-secondary"><%= @review.created_at.strftime('%Y/%m/%d') %></div>
                        </div>
                    </div>
                    <div class="flex space-x-2 items-center">
                        <% if @review.user == current_user %>
                            <%= render 'spots/crud_menus', review: @review %>
                        <% end %>
                    </div>
                </div>
                <div class="flex w-full items-center px-4 py-2 my-8">
                    <div class="flex gap-0.5">  
                        <% rating = @review.rating %>
                        <% full_stars = rating %>
                        <% empty_stars = 5 - rating %>
                        
                        <% full_stars.times do %>
                            <i class="ph-fill ph-star fa-lg text-yellow-400"></i>
                        <% end %>
                        
                        <% empty_stars.times do %>
                            <i class="ph-fill ph-star fa-lg text-gray-100"></i>
                        <% end %>
                    </div>
                </div>
                <p class="mb-8 text-base leading-relaxed text-left text-gray-500"><%= @review.body %></p>
                <div class="flex flex-wrap md:w-full px-4 w-11/12 mt-2 -mx-4 text-left md:space-x-4 space-x-2 mb-8">
                    <% if @review.tags.present? %>
                        <% @review.tags.each do |tag| %>
                            <%= link_to spots_path(tag_id: tag.id), class: "inline-flex text-secondary text-xs rounded-lg py-1.5 px-2 border border-secondary items-center hover:bg-primary-hover" do %>
                                <i class="ph ph-tag"></i>&nbsp;<%= tag.name %>
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
                <div class="flex justify-end w-full">
                    <div class="hidden md:block">
                        <%= link_to "https://twitter.com/share?url=https://nekospot.jp/spots/#{@review.spot.id}/reviews/#{@review.id}&text=#{ERB::Util.url_encode("「#{@review.spot.name}」の口コミを投稿しました🐈✨\n ##{@review.spot.name.gsub(/[\s()（）【】]/, '')} #NekoSpot \n")}", target: '_blank', class: "relative rounded px-5 py-2.5 overflow-hidden group bg-neutral relative hover:bg-gradient-to-r hover:from-neutral hover:to-secondary text-white hover:ring-2 hover:ring-offset-2 hover:ring-secondary transition-all ease-out duration-300" do %>
                                <span class="absolute right-0 w-8 h-32 -mt-12 transition-all duration-1000 transform translate-x-12 bg-white opacity-10 rotate-12 group-hover:-translate-x-40 ease"></span>
                                <span class="relative text-sm text-white dark:text-gray-400 "><i class="ph-bold ph-x-logo fa-lg w-6 h-3" aria-hidden="true"></i>シェア</span>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="md:hidden fixed bottom-20 right-4 z-10">
            <%= link_to "https://twitter.com/share?url=https://nekospot.jp/spots/#{@review.spot.id}/reviews/#{@review.id}&text=#{ERB::Util.url_encode("「#{@review.spot.name}」の口コミを投稿しました🐈✨\n ##{@review.spot.name.gsub(/[\s()（）【】]/, '')} #NekoSpot \n")}", target: '_blank', class: "relative rounded px-5 py-2.5 overflow-hidden group bg-neutral relative hover:bg-gradient-to-r hover:from-neutral hover:to-secondary text-white hover:ring-2 hover:ring-offset-2 hover:ring-secondary transition-all ease-out duration-300" do %>
                    <span class="absolute right-0 w-8 h-32 -mt-12 transition-all duration-1000 transform translate-x-12 bg-white opacity-10 rotate-12 group-hover:-translate-x-40 ease"></span>
                    <span class="relative text-sm text-white dark:text-gray-400 "><i class="ph-bold ph-x-logo fa-lg w-6 h-3" aria-hidden="true"></i>シェア</span>
            <% end %>
        </div>
    </div>
</section>

<script>
document.addEventListener("DOMContentLoaded", function() {
    const swiper = new Swiper('.swiper', {
        // Optional parameters
        direction: 'horizontal',
        loop: true,

        // If we need pagination
        pagination: {
            el: '.swiper-pagination',
        },

        // Navigation arrows
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },

        // And if we need scrollbar
        scrollbar: {
            el: '.swiper-scrollbar',
        },
    });
})
</script>